name: bus_application_project

services:
  postgres:
    image: postgres
    env_file:
      - .env
    container_name: postgres-container
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
