# Generated by Django 5.1.6 on 2025-05-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="description",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="bus",
            name="arrival_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="bus",
            name="departure_time",
            field=models.TimeField(),
        ),
    ]
