# Generated by Django 5.1.6 on 2025-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="town",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="town",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
