# Generated by Django 5.1.6 on 2025-05-18 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0002_town_latitude_town_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routestop",
            options={"ordering": ["position"]},
        ),
        migrations.RenameField(
            model_name="routestop",
            old_name="order",
            new_name="position",
        ),
        migrations.AlterUniqueTogether(
            name="routestop",
            unique_together={("route", "town")},
        ),
    ]
