# Generated by Django 5.1.6 on 2025-05-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0003_alter_routestop_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="towns",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="buses.town"
            ),
        ),
    ]
