# Generated by Django 5.1.6 on 2025-05-25 13:39
from django.db import migrations

def create_bus_companies(apps, schema_editor):
    Town = apps.get_model('buses', 'Town')
    BusCompany = apps.get_model('buses', 'BusCompany')

    companies_data = [
        {"name": "Galeb", "origin": "Ohrid", "reg": "GA123"},
        {"name": "Rule Turs", "origin": "Struga", "reg": "RT456"},
        {"name": "Halko Tours", "origin": "Skopje", "reg": "HT789"},
        {"name": "Sloboda Prevoz", "origin": "Skopje", "reg": "SP321"},
        {"name": "Durmo Tours", "origin": "Gostivar", "reg": "DT654"},
        {"name": "Besa Trans", "origin": "Tetovo", "reg": "BT987"},
        {"name": "Transkop", "origin": "Bitola", "reg": "TK741"},
        {"name": "Delfina Tours", "origin": "Kumanovo", "reg": "DF852"},
        {"name": "Euro Bus", "origin": "Prilep", "reg": "EB963"},
        {"name": "Makedonija Soobrakaj", "origin": "Shtip", "reg": "MS159"},
        {"name": "Avto Atom", "origin": "Kochani", "reg": "KO245"},
    ]

    for comp in companies_data:
        try:
            town = Town.objects.get(name=comp["origin"])
            BusCompany.objects.create(
                name=comp["name"],
                origin_town=town,
                registration_number=comp["reg"]
            )
        except Town.DoesNotExist:
            print(f"Town '{comp['origin']}' does not exist. Skipping...")

class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_create_macedonian_towns'),  # Replace with the actual previous migration name
    ]

    operations = [
        migrations.RunPython(create_bus_companies),
    ]

