# Generated by Django 5.1.6 on 2025-05-25 13:44
from django.db import migrations
from django.db.models import Case, When


def create_routes(apps, schema_editor):
    Town = apps.get_model('buses', 'Town')
    Route = apps.get_model('buses', 'Route')

    # Example routes: start town, end town, and list of towns in between
    routes_data = [
        ("Skopje", "Ohrid", ["Tetovo", "Gostivar", "Kichevo"]),
        ("Bitola", "Skopje", ["Prilep", "Veles"]),
        ("Struga", "Kumanovo", ["Ohrid", "Kichevo", "Tetovo", "Skopje"]),
        ("Shtip", "Tetovo", ["Sveti Nikole", "Veles", "Skopje"]),
        ("Prilep", "Kumanovo", ["Bitola", "Veles", "Skopje"]),
        ("Skopje", "Bitola", ["Veles", "Prilep"]),
        ("Ohrid", "Strumica", ["Resen", "Bitola", "Prilep", "Shtip"]),
        ("Kumanovo", "Ohrid", ["Skopje", "Tetovo", "Gostivar", "Kichevo"]),
        ("Skopje", "Struga", ["Tetovo", "Gostivar", "Kichevo"]),
        ("Shtip", "Prilep", ["Veles", "Bitola"]),
    ]

    more_routes_data = [
        ("Skopje", "Ohrid", ["Veles", "Prilep", "Bitola"]),
        ("Bitola", "Skopje", ["Resen", "Demir Hisar", "Kichevo", "Tetovo"]),
        ("Struga", "Kumanovo", ["Debar", "Gostivar", "Skopje"]),
        ("Shtip", "Tetovo", ["Kochani", "Kumanovo", "Skopje"]),
        ("Prilep", "Kumanovo", ["Bitola", "Demir Kapija", "Skopje"]),
        ("Skopje", "Bitola", ["Kumanovo", "Shtip", "Prilep"]),
        ("Ohrid", "Strumica", ["Debar", "Radovish"]),
        ("Kumanovo", "Ohrid", ["Kratovo", "Kichevo"]),
        ("Skopje", "Struga", ["Kumanovo", "Debar"]),
        ("Shtip", "Prilep", ["Kochani", "Demir Kapija"]),
        ("Ohrid", "Skopje", ["Bitola", "Prilep", "Veles"]),
        ("Skopje", "Bitola", ["Tetovo", "Kichevo", "Demir Hisar", "Resen"]),
        ("Kumanovo", "Struga", ["Skopje", "Gostivar", "Debar"]),
        ("Tetovo", "Shtip", ["Skopje", "Kumanovo", "Kochani"]),
        ("Kumanovo", "Prilep", ["Skopje", "Demir Kapija", "Bitola"]),
        ("Bitola", "Skopje", ["Prilep", "Shtip", "Kumanovo"]),
        ("Strumica", "Ohrid", ["Radovish", "Debar"]),
        ("Ohrid", "Kumanovo", ["Kichevo", "Kratovo"]),
        ("Struga", "Skopje", ["Debar", "Kumanovo"]),
        ("Prilep", "Shtip", ["Demir Kapija", "Kochani"]),
        ("Skopje", "Strumica", ["Veles", "Radovish"]),
        ("Strumica", "Skopje", ["Radovish", "Veles"]),
        ("Gostivar", "Bitola", ["Kichevo", "Prilep"]),
        ("Bitola", "Gostivar", ["Prilep", "Kichevo"]),
        ("Tetovo", "Ohrid", ["Gostivar", "Debar"]),
        ("Ohrid", "Tetovo", ["Debar", "Gostivar"]),
        ("Kumanovo", "Bitola", ["Shtip", "Prilep"]),
        ("Bitola", "Kumanovo", ["Prilep", "Shtip"]),
        ("Resen", "Kumanovo", ["Bitola", "Prilep", "Skopje"]),
        ("Kumanovo", "Resen", ["Skopje", "Prilep", "Bitola"]),
        ("Kochani", "Ohrid", ["Shtip", "Prilep", "Bitola"]),
        ("Ohrid", "Kochani", ["Bitola", "Prilep", "Shtip"]),
        ("Veles", "Gostivar", ["Skopje", "Tetovo"]),
        ("Gostivar", "Veles", ["Tetovo", "Skopje"]),
        ("Kratovo", "Struga", ["Kumanovo", "Skopje", "Debar"]),
        ("Struga", "Kratovo", ["Debar", "Skopje", "Kumanovo"]),
        ("Radovish", "Tetovo", ["Strumica", "Skopje"]),
        ("Tetovo", "Radovish", ["Skopje", "Strumica"]),
        ("Kochani", "Bitola", ["Shtip", "Prilep"]),
        ("Bitola", "Kochani", ["Prilep", "Shtip"]),
        ("Resen", "Strumica", ["Bitola", "Prilep", "Radovish"]),
        ("Strumica", "Resen", ["Radovish", "Prilep", "Bitola"]),
        ("Demir Kapija", "Ohrid", ["Prilep", "Bitola"]),
        ("Ohrid", "Demir Kapija", ["Bitola", "Prilep"]),
        ("Debar", "Shtip", ["Gostivar", "Skopje", "Kumanovo"]),
        ("Shtip", "Debar", ["Kumanovo", "Skopje", "Gostivar"]),
    ]

    for start_name, end_name, mid_names in routes_data + more_routes_data:
        try:
            start = Town.objects.get(name=start_name)
            end = Town.objects.get(name=end_name)

            preserved_order = Case(
                *[When(name=name, then=pos) for pos, name in enumerate(mid_names)]
            )

            mid_towns = list(Town.objects.filter(name__in=mid_names).order_by(preserved_order))            

            route = Route.objects.create(start_town=start, end_town=end)
            route.towns.set(mid_towns)
            route.towns_order = [town.id for town in mid_towns]
            route.save()

        except Town.DoesNotExist as e:
            print(f"Error: {e}. Skipping route from {start_name} to {end_name}.")


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0011_route_towns_order'),  # Replace with the latest migration name
    ]

    operations = [
        migrations.RunPython(create_routes),
    ]
