# Generated by Django 5.1.6 on 2025-05-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0004_bus_towns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="towns",
        ),
        migrations.AddField(
            model_name="bus",
            name="towns",
            field=models.ManyToManyField(to="buses.town"),
        ),
    ]
