# Generated by Django 5.1.6 on 2025-05-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0005_remove_bus_towns_bus_towns"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="from_town",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_town",
                to="buses.town",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="to_town",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_town",
                to="buses.town",
            ),
        ),
    ]
