# Generated by Django 5.1.6 on 2025-05-25 14:00

from django.db import migrations, models
import random
import datetime


def create_buses_for_routes(apps, schema_editor):
    Bus = apps.get_model('buses', 'Bus')
    Route = apps.get_model('buses', 'Route')
    BusCompany = apps.get_model('buses', 'BusCompany')

    companies = list(BusCompany.objects.all())
    if not companies:
        # If no companies, just return
        return

    for route in Route.objects.all():
        company = random.choice(companies)

        # Generate a unique registration number and name for each bus
        reg_number = f"MK{random.randint(1000,9999)}"
        bus_name = f"Express {route.start_town.name} to {route.end_town.name}"

        # Set some default times and price
        departure_time = datetime.time(hour=8, minute=0)
        arrival_time = datetime.time(hour=12, minute=0)
        price = 15.00

        Bus.objects.create(
            name=bus_name,
            description=f"Bus route from {route.start_town.name} to {route.end_town.name}",
            registration_number=reg_number,
            company=company,
            route=route,
            departure_time=departure_time,
            arrival_time=arrival_time,
            price=price,
            # image left blank (null)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_populate_routes_part_two'),  # replace with the last migration name
    ]

    operations = [
        migrations.RunPython(create_buses_for_routes),
    ]
