# Generated by Django 5.1.6 on 2025-06-20 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0008_towndistance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="number_of_seats",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ticket",
            name="departure_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
