# Generated by Django 5.1.6 on 2025-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_populate_bus_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='towns_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
